# Generated by Django 3.0.5 on 2020-04-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.IntegerField(default=0)),
                ('brojPalacinaka', models.IntegerField(default=0)),
            ],
        ),
    ]
